run:
  tests: true

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - errcheck
    - goconst
    - gocritic
    - gofumpt
#    - revive
    - gosec
    - gosimple
    - govet
    - ineffassign
#    - misspell
    - nakedret
    - prealloc
    - exportloopref
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
#    - unused

issues:
  exclude-rules:
    - text: "Use of weak random number generator"
      linters:
        - gosec
    - text: "ST1003:"
      linters:
        - stylecheck
