run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 10m
  tests: true

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - goconst
    - gocritic
    - gofumpt
#    - revive
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - exportloopref
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
#    - unused
    - unparam

linters-settings:
  gosec:
    excludes:
      - G404

issues:
  max-issues-per-linter: 0
