// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: canine_chain/amm/pool.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Pool struct {
	Index  string       `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Name   string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Coins  []types.Coin `protobuf:"bytes,3,rep,name=coins,proto3" json:"coins"`
	AMM_Id uint32       `protobuf:"varint,4,opt,name=aMM_Id,json=aMMId,proto3" json:"aMM_Id,omitempty"`
	// sdk.Dec in string representation
	SwapFeeMulti    string `protobuf:"bytes,5,opt,name=swap_fee_multi,json=swapFeeMulti,proto3" json:"swap_fee_multi,omitempty"`
	MinLockDuration int64  `protobuf:"varint,6,opt,name=min_lock_duration,json=minLockDuration,proto3" json:"min_lock_duration,omitempty"`
	// sdk.Dec in string representation
	PenaltyMulti string `protobuf:"bytes,7,opt,name=penalty_multi,json=penaltyMulti,proto3" json:"penalty_multi,omitempty"`
	// Tracks amount of pool token
	PoolToken *types.Coin `protobuf:"bytes,8,opt,name=pool_token,json=poolToken,proto3" json:"pool_token,omitempty"`
}

func (m *Pool) Reset()         { *m = Pool{} }
func (m *Pool) String() string { return proto.CompactTextString(m) }
func (*Pool) ProtoMessage()    {}
func (*Pool) Descriptor() ([]byte, []int) {
	return fileDescriptor_119a277b84015fed, []int{0}
}
func (m *Pool) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Pool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Pool.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Pool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pool.Merge(m, src)
}
func (m *Pool) XXX_Size() int {
	return m.Size()
}
func (m *Pool) XXX_DiscardUnknown() {
	xxx_messageInfo_Pool.DiscardUnknown(m)
}

var xxx_messageInfo_Pool proto.InternalMessageInfo

func (m *Pool) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *Pool) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Pool) GetCoins() []types.Coin {
	if m != nil {
		return m.Coins
	}
	return nil
}

func (m *Pool) GetAMM_Id() uint32 {
	if m != nil {
		return m.AMM_Id
	}
	return 0
}

func (m *Pool) GetSwapFeeMulti() string {
	if m != nil {
		return m.SwapFeeMulti
	}
	return ""
}

func (m *Pool) GetMinLockDuration() int64 {
	if m != nil {
		return m.MinLockDuration
	}
	return 0
}

func (m *Pool) GetPenaltyMulti() string {
	if m != nil {
		return m.PenaltyMulti
	}
	return ""
}

func (m *Pool) GetPoolToken() *types.Coin {
	if m != nil {
		return m.PoolToken
	}
	return nil
}

func init() {
	proto.RegisterType((*Pool)(nil), "canine_chain.amm.Pool")
}

func init() { proto.RegisterFile("canine_chain/amm/pool.proto", fileDescriptor_119a277b84015fed) }

var fileDescriptor_119a277b84015fed = []byte{
	// 372 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xcd, 0xaa, 0xd4, 0x30,
	0x1c, 0xc5, 0x9b, 0x3b, 0xed, 0xe8, 0x8d, 0x5e, 0x3f, 0xc2, 0x15, 0xea, 0x15, 0x6a, 0x51, 0x17,
	0x45, 0x30, 0xe1, 0x2a, 0x82, 0xeb, 0x51, 0xc4, 0x81, 0x29, 0x48, 0x71, 0xe5, 0xa6, 0xa4, 0x69,
	0x9c, 0x89, 0x6d, 0xf2, 0x2f, 0xd3, 0x8c, 0xce, 0xbc, 0x85, 0x6f, 0xe2, 0x6b, 0xcc, 0x72, 0x96,
	0xae, 0x44, 0x66, 0x5e, 0x44, 0xd2, 0x74, 0xe1, 0xca, 0xdd, 0xe9, 0xaf, 0x27, 0xe7, 0x90, 0x1c,
	0xfc, 0x48, 0x70, 0xa3, 0x8c, 0x2c, 0xc5, 0x8a, 0x2b, 0xc3, 0xb8, 0xd6, 0xac, 0x03, 0x68, 0x69,
	0xb7, 0x06, 0x0b, 0xe4, 0xde, 0xbf, 0x3f, 0x29, 0xd7, 0xfa, 0x2a, 0x11, 0xd0, 0x6b, 0xe8, 0x59,
	0xc5, 0x7b, 0xc9, 0xbe, 0x5d, 0x57, 0xd2, 0xf2, 0x6b, 0x26, 0x40, 0x19, 0x7f, 0xe2, 0xea, 0x72,
	0x09, 0x4b, 0x18, 0x24, 0x73, 0xca, 0xd3, 0x27, 0x3f, 0xcf, 0x70, 0xf8, 0x11, 0xa0, 0x25, 0x97,
	0x38, 0x52, 0xa6, 0x96, 0xdb, 0x18, 0xa5, 0x28, 0x3b, 0x2f, 0xfc, 0x07, 0x21, 0x38, 0x34, 0x5c,
	0xcb, 0xf8, 0x6c, 0x80, 0x83, 0x26, 0xaf, 0x71, 0xe4, 0x62, 0xfb, 0x78, 0x92, 0x4e, 0xb2, 0x5b,
	0x2f, 0x1f, 0x52, 0x5f, 0x4c, 0x5d, 0x31, 0x1d, 0x8b, 0xe9, 0x5b, 0x50, 0x66, 0x16, 0xee, 0x7f,
	0x3f, 0x0e, 0x0a, 0xef, 0x26, 0x0f, 0xf0, 0x94, 0xe7, 0x79, 0x39, 0xaf, 0xe3, 0x30, 0x45, 0xd9,
	0x45, 0x11, 0xf1, 0x3c, 0x9f, 0xd7, 0xe4, 0x19, 0xbe, 0xd3, 0x7f, 0xe7, 0x5d, 0xf9, 0x45, 0xca,
	0x52, 0x6f, 0x5a, 0xab, 0xe2, 0x68, 0xe8, 0xba, 0xed, 0xe8, 0x7b, 0x29, 0x73, 0xc7, 0xc8, 0x73,
	0x7c, 0x5f, 0x2b, 0x53, 0xb6, 0x20, 0x9a, 0xb2, 0xde, 0xac, 0xb9, 0x55, 0x60, 0xe2, 0x69, 0x8a,
	0xb2, 0x49, 0x71, 0x57, 0x2b, 0xb3, 0x00, 0xd1, 0xbc, 0x1b, 0x31, 0x79, 0x8a, 0x2f, 0x3a, 0x69,
	0x78, 0x6b, 0x77, 0x63, 0xe0, 0x0d, 0x1f, 0x38, 0x42, 0x1f, 0xf8, 0x06, 0x63, 0xf7, 0x9a, 0xa5,
	0x85, 0x46, 0x9a, 0xf8, 0x66, 0x8a, 0xfe, 0x7b, 0x93, 0xe2, 0xdc, 0x99, 0x3f, 0x39, 0xef, 0xec,
	0xc3, 0xfe, 0x98, 0xa0, 0xc3, 0x31, 0x41, 0x7f, 0x8e, 0x09, 0xfa, 0x71, 0x4a, 0x82, 0xc3, 0x29,
	0x09, 0x7e, 0x9d, 0x92, 0xe0, 0x33, 0x5d, 0x2a, 0xbb, 0xda, 0x54, 0x54, 0x80, 0x66, 0x5f, 0xb9,
	0x68, 0x78, 0xbb, 0xe0, 0x55, 0xcf, 0xfc, 0x52, 0x2f, 0xfc, 0x8c, 0xdb, 0x61, 0x48, 0xbb, 0xeb,
	0x64, 0x5f, 0x4d, 0x87, 0x09, 0x5e, 0xfd, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x21, 0x45, 0x12, 0x41,
	0xe9, 0x01, 0x00, 0x00,
}

func (m *Pool) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Pool) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Pool) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PoolToken != nil {
		{
			size, err := m.PoolToken.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPool(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x42
	}
	if len(m.PenaltyMulti) > 0 {
		i -= len(m.PenaltyMulti)
		copy(dAtA[i:], m.PenaltyMulti)
		i = encodeVarintPool(dAtA, i, uint64(len(m.PenaltyMulti)))
		i--
		dAtA[i] = 0x3a
	}
	if m.MinLockDuration != 0 {
		i = encodeVarintPool(dAtA, i, uint64(m.MinLockDuration))
		i--
		dAtA[i] = 0x30
	}
	if len(m.SwapFeeMulti) > 0 {
		i -= len(m.SwapFeeMulti)
		copy(dAtA[i:], m.SwapFeeMulti)
		i = encodeVarintPool(dAtA, i, uint64(len(m.SwapFeeMulti)))
		i--
		dAtA[i] = 0x2a
	}
	if m.AMM_Id != 0 {
		i = encodeVarintPool(dAtA, i, uint64(m.AMM_Id))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Coins) > 0 {
		for iNdEx := len(m.Coins) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Coins[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPool(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintPool(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintPool(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintPool(dAtA []byte, offset int, v uint64) int {
	offset -= sovPool(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Pool) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovPool(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovPool(uint64(l))
	}
	if len(m.Coins) > 0 {
		for _, e := range m.Coins {
			l = e.Size()
			n += 1 + l + sovPool(uint64(l))
		}
	}
	if m.AMM_Id != 0 {
		n += 1 + sovPool(uint64(m.AMM_Id))
	}
	l = len(m.SwapFeeMulti)
	if l > 0 {
		n += 1 + l + sovPool(uint64(l))
	}
	if m.MinLockDuration != 0 {
		n += 1 + sovPool(uint64(m.MinLockDuration))
	}
	l = len(m.PenaltyMulti)
	if l > 0 {
		n += 1 + l + sovPool(uint64(l))
	}
	if m.PoolToken != nil {
		l = m.PoolToken.Size()
		n += 1 + l + sovPool(uint64(l))
	}
	return n
}

func sovPool(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPool(x uint64) (n int) {
	return sovPool(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Pool) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPool
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Pool: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Pool: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coins", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Coins = append(m.Coins, types.Coin{})
			if err := m.Coins[len(m.Coins)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AMM_Id", wireType)
			}
			m.AMM_Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AMM_Id |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwapFeeMulti", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SwapFeeMulti = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinLockDuration", wireType)
			}
			m.MinLockDuration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinLockDuration |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PenaltyMulti", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PenaltyMulti = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolToken", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PoolToken == nil {
				m.PoolToken = &types.Coin{}
			}
			if err := m.PoolToken.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPool(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPool
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPool(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPool
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPool
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPool
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPool
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPool
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPool
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPool        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPool          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPool = fmt.Errorf("proto: unexpected end of group")
)
