name: Unit Test

on:
  pull_request:
  push:
    branches: ["master"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.2 # The Go version to download (if necessary) and use.
      - name: Test
        shell: bash
        run: make test-unit
